### ISSUE TITLE
Не инклюдить заголовки, которые не используются

### ISSUE THREAD

**Issue by olgapshen** [DarkHunteR73/search_engine#2]
https://github.com/DarkHunteR73/search_engine/blob/bd949b92c0fe326ad52c1f8cbe3ed3ec1de1ccc1/include/searchServer.h#L5

invertedIndex.h не надо тянуть. Надо тянуть только то, что собираешься использовать, и даже если собираешься использовать но в виде указателя, тогда нужно использовать предварительное определение и тоже не тянуть заголовок: https://www.geeksforgeeks.org/what-are-forward-declarations-in-c/

Тут например <mutex> не используется, его надо перенести в файл реализации.

**Comment by DarkHunteR73** [comment]
Тут ведь не указатель, а непосредственно объект. Выдаст ошибку, что поле имеет неполный тип

**Comment by olgapshen** [comment]
Да, но в заголовке у тебя нет ни одного поля этого типа и ни одной функции.
Надо в файл реализации перенести.

**Comment by DarkHunteR73** [comment]
[search_engine/include/searchServer.h](https://github.com/DarkHunteR73/search_engine/blob/64a74c9da6290cd6788b1f6c983918f7e14c0660/include/searchServer.h#L35)

Вот же оно

**Comment by DarkHunteR73** [comment]
Остальные инклюды перенёс, кстати

**Comment by DarkHunteR73** [comment]
Вот так сделал: https://github.com/DarkHunteR73/search_engine/commit/2e001949f16e7b880c431f560f15d6aee782a8df

C:/Users/DarkHunteR7/source/repos/search_engine/include/searchServer.h:37:19: error: field 'm_index' has incomplete type 'invertedIndex'
   37 |     invertedIndex m_index;

**Comment by olgapshen** [comment]
Но `invertedIndex m_index;` это не `thread`... я же про то, что тебе не нужен `thread` в том заголовке. Нет?

**Comment by olgapshen** [comment]
Я про то, что в `invertedIndex.h` нет надобности в `#include <thread>`

**Comment by olgapshen** [comment]
`#include "invertedIndex.h"` в `searchServer.h` - ножОн, а `#include <thread>` в `invertedIndex.h` - нет.

**Comment by olgapshen** [comment]
Ты можешь сделать отдельные MR-ы в свою нынешнюю ветку - develop, тогда сделаем code review, сольём и закроем задачу.

**Comment by olgapshen** [comment]
Так, я вижу это ты тоже сделал: https://github.com/DarkHunteR73/search_engine/commit/28f0e1732c23e29bd843330a256a0a43b187e657

**Comment by olgapshen** [comment]
Вот, ещё этот MR слить.
