### ISSUE TITLE
Объеденить CMaleList-ы

### ISSUE THREAD

**Issue by olgapshen** [DarkHunteR73/search_engine#3]
https://github.com/DarkHunteR73/search_engine/blob/bd949b92c0fe326ad52c1f8cbe3ed3ec1de1ccc1/src/CMakeLists.txt#L1

У тебя CMaleLists.txt в папке src и один в корне. Если это не оговорено в ТЗ, то лучше один сделать.
Посмотрела ТЗ, кажись не оговорено.

**Comment by DarkHunteR73** [comment]
https://github.com/DarkHunteR73/search_engine/commit/db15a10c97401a53fa9315186b865c037609ed11

**Comment by olgapshen** [comment]
Круто! Если собирается - делай MR

**Comment by olgapshen** [comment]
Это я вижу ты уже объединил, можно закрывать.
